version: "3.9"

services:
  elden-api:
    build: .
    container_name: eldenringapi
    ports:
      - "8000:8000"
    environment:
      - DATA_DIR=/data
      - SECRET_KEY=CHANGE_THIS_SECRET
    volumes:
      - ./data:/data:ro