services:
  - type: web
    name: eldenring-api
    runtime: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATA_DIR
        value: /app/data
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /